language: clojure
lein: lein
script: lein do clean, check, test
jdk:
  - oraclejdk9
before_script:
  - "export DISPLAY=:90.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
